name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y libtool libtool-bin autoconf automake pkg-config zip unzip openjdk-17-jdk build-essential
